name: piggie_bank
description: A minimalistic money manager application

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  charts_flutter: ^0.9.0
  json_annotation:
  http:

    
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
